#服务的名称
spring:
  application:
    name: p2p-dataservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/p2p
    username: root
    password: 123
#配置dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  #扫描包
  scan:
    base-packages: com.bjpowernode.p2p.service
  #提供者的默认配置
  provider:
    timeout: 5000
  #默认是dubbo协议
  protocol:
    name: dubbo

#mybatis
mybatis:
  #mapper文件
  mapper-locations: classpath:mappers/**/*.xml
  #日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.bjpowernode.p2p.model