server:
  port: 8080
  servlet:
    context-path: /p2p

#模板引擎
spring:
  thymeleaf:
    cache: false
    mode: HTML
  application:
    name: p2p2-web
  redis:
    host: 81.70.162.104
    port: 6379
#dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.web
  consumer:
    retries: 0
    check: false