server:
  port: 8080
  servlet:
    context-path: /p2p
#模板引擎
spring:
  thymeleaf:
    cache: false
    mode: HTML
  application:
    name: p2p2-web
#dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.web
  consumer:
    retries: 0
    check: false