server:
  port: 8080
  servlet:
    context-path: /p2p

#模板引擎
spring:
  thymeleaf:
    cache: false
    mode: HTML
  application:
    name: p2p-web
  redis:
    host: 81.70.162.104
    port: 6379
  session:
    store-type: redis
    timeout: PT60M
#dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.web
  consumer:
    retries: 0
    check: false
#spring session

txcloud:
  secretId: AKID3TjV25IvTfqkvnwJki5Fi6j19Q71F9AL8p7A
  secretKey: 7JUDxfDcKDCUr1Uu78L44sxIefF2tV1T9QAAdlSS